language: go
go:
  - "1.11.x"
sudo: false
env:
  global:
    - "GO111MODULE=on"
go_import_path: "go.linecorp.com/centraldogma"
install:
  - go get -v go.linecorp.com/centraldogma
  - go get -v go.linecorp.com/centraldogma/internal/app/dogma
script:
  - go test -v go.linecorp.com/centraldogma
  - go test -v go.linecorp.com/centraldogma/internal/app/dogma
notifications:
  email: false
cache:
  directories:
    - "$GOPATH/pkg/mod/cache"
